api/urls.py
from rest_framework.routers import DefaultRouter
from api.views import BookReviewViewSet

app_name = 'api'

router = DefaultRouter()
router.register('reviews', BookReviewViewSet, basename='review')

# urlpatterns = [
#     path("reviews/", BookReviewsAPIView.as_view(), name="review-list"),
#     path("reviews/<int:id>/", BookReviewDetailAPIView.as_view(), name="review-detail"),
# ]

urlpatterns = router.urls

goodreads/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from .views import landing_page, home_page


urlpatterns = [
    path('', landing_page, name='landing_page'),
    path("home/", home_page, name='home_page'),
    path("users/", include('users.urls')),
    path("books/", include('books.urls')),
    path("api/", include('api.urls')),

    path('admin/', admin.site.urls),
    path("api-auth/", include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView


app_name = 'users'
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile-edit"),
]

users/models.py
from django.contrib.auth.models import AbstractUser

from django.db import models


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="default_profile_pic.jpg")

users/forms.py
from django import forms
from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', "profile_picture")

users/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages


from users.forms import UserCreateForm, UserUpdateForm


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            "form": create_form
        }
        return render(request, 'users/register.html', context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
            return redirect("users:login")
        else:
            context = {
                "form": create_form
            }
            return render(request, 'users/register.html', context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()

        return render(request, "users/login.html", {"login_form": login_form})

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, "You have successfully logged in.")
            return redirect("books:list")
        else:
            return render(request, "users/login.html", {"login_form": login_form})


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "users/profile.html", {"user": request.user})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, f"You have successfully logged out.")
        return redirect("landing_page")


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        return render(request, "users/profile_edit.html", {"form": user_update_form})

    def post(self, request):
        user_update_form = UserUpdateForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES
        )

        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, "You have successfully updated your profile.")
            return redirect("users:profile")

        return render(request, "users/profile_edit.html", {"form": user_update_form})

users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login page{% endblock title %}

{% block content %}
    <h3>Login</h3>

        <div class="row">
            <div class="col-4">
                <form method="post" class="d-grid gap-2">
                    {% csrf_token %}
                    {{ login_form | crispy }}

                    <button class="btn btn-outline-info">Login</button> <span class="ms-3">No account? Then, <a href="{% url "users:register" %}"> get registred</a></span>
                </form>
            </div>
        </div>


{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}


{% block title %}Profile page{% endblock title %}


{% block content %}
    <div class="image d-flex flex-column justify-content-center align-items-center">
{#        <button class="btn btn-secondary">#}
        <img class="profile_pic" alt="Profile picture" src="{{ user.profile_picture.url }}">
{#        </button>#}
        <span class="name mt-3">{{ user.first_name }} {{ user.last_name }}</span>
        <span class="idd">@{{ user.username }}</span>
        <span class="idd">{{ user.email}}</span>
        <div class="d-flex mt-2"><a class="btn btn-dark" href="{% url "users:profile-edit" %}">Edit profile</a></div>
        <div class="px-2 rounded mt-4 date"><span class="join">Joined {{ user.date_joined | date:"M d, Y"  }}</span> </div>
    </div>

{% endblock content %}

users/templates/users/profile_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h3>Edit profile</h3>

    <div class="row">
        <div class="col-4">
            <form method="post" enctype="multipart/form-data" class="d-grid gap-2">
                {% csrf_token %}

                {{ form | crispy }}

                <button class="btn btn-primary">Save changes</button>
            </form>
        </div>
    </div>

{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Register Page{% endblock title %}

{% block content %}
    <h3>Register new account</h3>

    <div class="row">
        <div class="col-4">
            <form method="post" action="{% url "users:register" %}" class="d-grid gap-2">
                {% csrf_token %}

                {{ form | crispy }}

                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>

{% endblock content %}