api/urls.py
from rest_framework.routers import DefaultRouter
from api.views import BookReviewViewSet

app_name = 'api'

router = DefaultRouter()
router.register('reviews', BookReviewViewSet, basename='review')

# urlpatterns = [
#     path("reviews/", BookReviewsAPIView.as_view(), name="review-list"),
#     path("reviews/<int:id>/", BookReviewDetailAPIView.as_view(), name="review-detail"),
# ]

urlpatterns = router.urls

books/urls.py
from django.urls import path
from books.views import (BooksView,
                         BookDetailView,
                         AddReviewView,
                         EditReviewView,
                         ConfirmDeleteReviewView,
                         DeleteReviewView,
                         )

app_name = 'books'
urlpatterns = [
    path('', BooksView.as_view(), name='list'),
    path("<int:id>/", BookDetailView.as_view(), name='detail'),
    path("<int:id>/reviews/", AddReviewView.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/edit/', EditReviewView.as_view(), name='edit-review'),
    path(
        '<int:book_id>/reviews/<int:review_id>/delete/confirm/',
        ConfirmDeleteReviewView.as_view(),
        name='confirm-delete-review'
    ),
    path(
        '<int:book_id>/reviews/<int:review_id>/delete/',
        DeleteReviewView.as_view(),
        name='delete-review'
    ),

]

goodreads/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from .views import landing_page, home_page


urlpatterns = [
    path('', landing_page, name='landing_page'),
    path("home/", home_page, name='home_page'),
    path("users/", include('users.urls')),
    path("books/", include('books.urls')),
    path("api/", include('api.urls')),

    path('admin/', admin.site.urls),
    path("api-auth/", include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView


app_name = 'users'
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile-edit"),
]

templates/base.html
{% load static %}
{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url "users:profile" as profile_page_url %}
{% url "users:profile-edit" as profile_edit_page_url %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Goodreads Clone{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
{#    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">#}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body class="mx-5">
    <nav class="navbar navbar-expand-lg navbar-dark mb-4 bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads Clone</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{{ home_page_url }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == books_page_url %} active {% endif %}" aria-current="page" href="{{ books_page_url }}">Books</a>
            </li>
          </ul>
            <div class="me-5">
                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle {% if request.path == profile_page_url or request.path == profile_edit_page_url %} active {% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ request.user.username }}
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{ profile_page_url }}">Profile</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url "users:logout" %}">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                {% else %}
                    <a class="btn btn-outline-info" href="{% url 'users:login' %}">Login</a>
                {% endif %}

            </div>
        </div>
      </div>
    </nav>
    
    <div class="container">
        {% if messages %}
            <div class="mt-4">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    
        {% block content %}
            
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Home Page {% endblock title %}

{% block content %}
    <h3>All reviews</h3>

    {% for review in page_obj %}
        <div class="container posts-content">
            <div class="row">
                <div class="col-lg-6">
                    <div class="card mb-4">
                      <div class="card-body">
                        <div class="media mb-3">
                          <img src="{{ review.user.profile_picture.url }}" class="d-block ui-w-40 rounded-circle" alt="">
                          <div class="media-body ml-3">
                            <b>{{ review.user.username }}</b> rated this book {{ review.stars_given }} stars
                            <div class="text-muted small">{{ review.created_at | date:"M d, Y" }}</div>
                          </div>
                        </div>

                        <p>
                          {{ review.comment | truncatechars:300 }}
                        </p>
                        <img src="{{ review.book.cover_picture.url }}" class="cover_pic center">
{#                        <a href="javascript:void(0)" class="ui-rect ui-bg-cover" style="background-image: url({{ review.book.cover_picture.url }});"></a>#}
                      </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a> </li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
            {% endif %}

            <li class="page-item active">
                <a href="#" class="page-link">{{ page_obj.number }}</a>
            </li>

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a> </li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a> </li>
            {% endif %}
        </ul>
    </nav>
{% endblock content %}

templates/landing.html
{% extends "base.html" %}

    {% block content %}
        <h1>Landing page</h1>

        <p>
            Deciding what to read next?
            You’re in the right place. Tell us what titles or genres you’ve enjoyed in the past, and we’ll give you surprisingly insightful recommendations.
        </p>
        <p>
            What are your friends reading?
            Chances are your friends are discussing their favorite (and least favorite) books on Goodreads.
        </p>
    {% endblock %}